# Site settings
title: "sptnkmmnt - хранилище текстов"
description: "Sputnik Moment text repository"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "http://sputnikmoment.ru"
author: "sptnkmmnt"

# Build settings
kramdown:
  input: GFM
permalink: /:title:output_ext

# Third-party services
# just leave empty to disable it
google_analytics: UA-87081507-1
disqus_shortname: sputnikmoment 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
